<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace chase_test_4\speakeasy_aPI\Models\Operations;

use \chase_test_4\speakeasy_aPI\Utils\SpeakeasyMetadata;
class FindApiEndpointRequest
{
    /**
     * The ID of the Api the ApiEndpoint belongs to.
     * 
     * @var string $apiID
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=apiID')]
    public string $apiID;
    
    /**
     * The displayName of the ApiEndpoint to find (set by operationId from OpenAPI schema).
     * 
     * @var string $displayName
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=displayName')]
    public string $displayName;
    
    /**
     * The version ID of the Api the ApiEndpoint belongs to.
     * 
     * @var string $versionID
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=versionID')]
    public string $versionID;
    
	public function __construct()
	{
		$this->apiID = "";
		$this->displayName = "";
		$this->versionID = "";
	}
}
