<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace chase_test_4\speakeasy_aPI\Models\Operations;

use \chase_test_4\speakeasy_aPI\Utils\SpeakeasyMetadata;
class GetAllApiVersionsRequest
{
    /**
     * The ID of the Api to retrieve.
     * 
     * @var string $apiID
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=apiID')]
    public string $apiID;
    
    /**
     * Metadata to filter Apis on
     * 
     * @var ?array<string, array<string>> $metadata
     */
	#[SpeakeasyMetadata('queryParam:style=deepObject,explode=true,name=metadata')]
    public ?array $metadata = null;
    
    /**
     * Configuration for filter operations
     * 
     * @var ?\chase_test_4\speakeasy_aPI\Models\Operations\GetAllApiVersionsOp $op
     */
	#[SpeakeasyMetadata('queryParam:style=deepObject,explode=true,name=op')]
    public ?GetAllApiVersionsOp $op = null;
    
	public function __construct()
	{
		$this->apiID = "";
		$this->metadata = null;
		$this->op = null;
	}
}
