<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace chase_test_4\speakeasy_aPI\Models\Operations;

use \chase_test_4\speakeasy_aPI\Utils\SpeakeasyMetadata;
class GetSchemaDiffRequest
{
    /**
     * The ID of the Api to retrieve schemas for.
     * 
     * @var string $apiID
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=apiID')]
    public string $apiID;
    
    /**
     * The base revision ID of the schema to retrieve.
     * 
     * @var string $baseRevisionID
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=baseRevisionID')]
    public string $baseRevisionID;
    
    /**
     * The target revision ID of the schema to retrieve.
     * 
     * @var string $targetRevisionID
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=targetRevisionID')]
    public string $targetRevisionID;
    
    /**
     * The version ID of the Api to delete metadata for.
     * 
     * @var string $versionID
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=versionID')]
    public string $versionID;
    
	public function __construct()
	{
		$this->apiID = "";
		$this->baseRevisionID = "";
		$this->targetRevisionID = "";
		$this->versionID = "";
	}
}
