<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace chase_test_4\speakeasy_aPI\Models\Operations;

use \chase_test_4\speakeasy_aPI\Utils\SpeakeasyMetadata;
class InsertVersionMetadataRequest
{
    /**
     * A JSON representation of the metadata to insert.
     * 
     * @var \chase_test_4\speakeasy_aPI\Models\Shared\VersionMetadataInput $versionMetadataInput
     */
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \chase_test_4\speakeasy_aPI\Models\Shared\VersionMetadataInput $versionMetadataInput;
    
    /**
     * The ID of the Api to insert metadata for.
     * 
     * @var string $apiID
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=apiID')]
    public string $apiID;
    
    /**
     * The version ID of the Api to insert metadata for.
     * 
     * @var string $versionID
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=versionID')]
    public string $versionID;
    
	public function __construct()
	{
		$this->versionMetadataInput = new \chase_test_4\speakeasy_aPI\Models\Shared\VersionMetadataInput();
		$this->apiID = "";
		$this->versionID = "";
	}
}
