<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace chase_test_4\speakeasy_aPI\Models\Operations;

use \chase_test_4\speakeasy_aPI\Utils\SpeakeasyMetadata;
class RegisterSchemaRequest
{
    /**
     * The schema file to upload provided as a multipart/form-data file segment.
     * 
     * @var \chase_test_4\speakeasy_aPI\Models\Operations\RegisterSchemaRequestBody $requestBody
     */
	#[SpeakeasyMetadata('request:mediaType=multipart/form-data')]
    public RegisterSchemaRequestBody $requestBody;
    
    /**
     * The ID of the Api to get the schema for.
     * 
     * @var string $apiID
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=apiID')]
    public string $apiID;
    
    /**
     * The version ID of the Api to delete metadata for.
     * 
     * @var string $versionID
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=versionID')]
    public string $versionID;
    
	public function __construct()
	{
		$this->requestBody = new \chase_test_4\speakeasy_aPI\Models\Operations\RegisterSchemaRequestBody();
		$this->apiID = "";
		$this->versionID = "";
	}
}
