<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace chase_test_4\speakeasy_aPI\Models\Operations;

use \chase_test_4\speakeasy_aPI\Utils\SpeakeasyMetadata;
class RevokeEmbedAccessTokenRequest
{
    /**
     * The ID of the EmbedToken to revoke.
     * 
     * @var string $tokenID
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=tokenID')]
    public string $tokenID;
    
	public function __construct()
	{
		$this->tokenID = "";
	}
}
