<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace chase_test_4\speakeasy_aPI\Models\Operations;

use \chase_test_4\speakeasy_aPI\Utils\SpeakeasyMetadata;
class UpsertApiRequest
{
    /**
     * A JSON representation of the Api to upsert
     * 
     * @var \chase_test_4\speakeasy_aPI\Models\Shared\ApiInput $apiInput
     */
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \chase_test_4\speakeasy_aPI\Models\Shared\ApiInput $apiInput;
    
    /**
     * The ID of the Api to upsert.
     * 
     * @var string $apiID
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=apiID')]
    public string $apiID;
    
	public function __construct()
	{
		$this->apiInput = new \chase_test_4\speakeasy_aPI\Models\Shared\ApiInput();
		$this->apiID = "";
	}
}
