<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace chase_test_4\speakeasy_aPI\Models\Shared;


/**
 * EmbedAccessTokenResponse - An EmbedAccessTokenResponse contains a token that can be used to embed a Speakeasy dashboard.
 * 
 * @package chase_test_4\speakeasy_aPI\Models\Shared
 * @access public
 */
class EmbedAccessTokenResponse
{
	#[\JMS\Serializer\Annotation\SerializedName('access_token')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $accessToken;
    
	public function __construct()
	{
		$this->accessToken = "";
	}
}
