<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace chase_test_4\speakeasy_aPI;

class Requests 
{

	private SDKConfiguration $sdkConfiguration;

	/**
	 * @param SDKConfiguration $sdkConfig
	 */
	public function __construct(SDKConfiguration $sdkConfig)
	{
		$this->sdkConfiguration = $sdkConfig;
	}
	
    /**
     * Generate a Postman collection for a particular request.
     * 
     * Generates a Postman collection for a particular request. 
     * Allowing it to be replayed with the same inputs that were captured by the SDK.
     * 
     * @param \chase_test_4\speakeasy_aPI\Models\Operations\GenerateRequestPostmanCollectionRequest $request
     * @return \chase_test_4\speakeasy_aPI\Models\Operations\GenerateRequestPostmanCollectionResponse
     */
	public function generateRequestPostmanCollection(
        ?\chase_test_4\speakeasy_aPI\Models\Operations\GenerateRequestPostmanCollectionRequest $request,
    ): \chase_test_4\speakeasy_aPI\Models\Operations\GenerateRequestPostmanCollectionResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/v1/eventlog/{requestID}/generate/postman', \chase_test_4\speakeasy_aPI\Models\Operations\GenerateRequestPostmanCollectionRequest::class, $request);
        
        $options = ['http_errors' => false];
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \chase_test_4\speakeasy_aPI\Models\Operations\GenerateRequestPostmanCollectionResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $response->postmanCollection = $httpResponse->getBody()->getContents();
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->error = $serializer->deserialize((string)$httpResponse->getBody(), 'chase_test_4\speakeasy_aPI\Models\Shared\Error', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Get information about a particular request.
     * 
     * @param \chase_test_4\speakeasy_aPI\Models\Operations\GetRequestFromEventLogRequest $request
     * @return \chase_test_4\speakeasy_aPI\Models\Operations\GetRequestFromEventLogResponse
     */
	public function getRequestFromEventLog(
        ?\chase_test_4\speakeasy_aPI\Models\Operations\GetRequestFromEventLogRequest $request,
    ): \chase_test_4\speakeasy_aPI\Models\Operations\GetRequestFromEventLogResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/v1/eventlog/{requestID}', \chase_test_4\speakeasy_aPI\Models\Operations\GetRequestFromEventLogRequest::class, $request);
        
        $options = ['http_errors' => false];
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \chase_test_4\speakeasy_aPI\Models\Operations\GetRequestFromEventLogResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->unboundedRequest = $serializer->deserialize((string)$httpResponse->getBody(), 'chase_test_4\speakeasy_aPI\Models\Shared\UnboundedRequest', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->error = $serializer->deserialize((string)$httpResponse->getBody(), 'chase_test_4\speakeasy_aPI\Models\Shared\Error', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Query the event log to retrieve a list of requests.
     * 
     * Supports retrieving a list of request captured by the SDK for this workspace.
     * Allows the filtering of requests on a number of criteria such as ApiID, VersionID, Path, Method, etc.
     * 
     * @param \chase_test_4\speakeasy_aPI\Models\Operations\QueryEventLogRequest $request
     * @return \chase_test_4\speakeasy_aPI\Models\Operations\QueryEventLogResponse
     */
	public function queryEventLog(
        ?\chase_test_4\speakeasy_aPI\Models\Operations\QueryEventLogRequest $request,
    ): \chase_test_4\speakeasy_aPI\Models\Operations\QueryEventLogResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/v1/eventlog/query');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\chase_test_4\speakeasy_aPI\Models\Operations\QueryEventLogRequest::class, $request, null));
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \chase_test_4\speakeasy_aPI\Models\Operations\QueryEventLogResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->boundedRequests = $serializer->deserialize((string)$httpResponse->getBody(), 'array<chase_test_4\speakeasy_aPI\Models\Shared\BoundedRequest>', 'json');
            }
        }
        else {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->error = $serializer->deserialize((string)$httpResponse->getBody(), 'chase_test_4\speakeasy_aPI\Models\Shared\Error', 'json');
            }
        }

        return $response;
    }
}