<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace chase_test_4\speakeasy_aPI;

class SDKConfiguration
{
	public ?\GuzzleHttp\ClientInterface $defaultClient = null;
	public ?\GuzzleHttp\ClientInterface $securityClient = null;
	public ?Models\Shared\Security $security = null;
	public string $serverUrl = '';
	public string $server = '';
	public string $language = 'php';
	public string $openapiDocVersion = '0.1.0';
	public string $sdkVersion = '0.1.0';
	public string $genVersion = '2.169.0';
	public string $userAgent = 'speakeasy-sdk/php 0.1.0 2.169.0 0.1.0 chase-test-4/speakeasy-api';
	

	public function getServerUrl(): string
	{
		
		if ($this->serverUrl !== '') {
			return $this->serverUrl;
		}
		if ($this->server === '') {
			$this->server = SpeakeasyAPI::SERVER_PROD;
		}

		return SpeakeasyAPI::SERVERS[$this->server];
	}
	
}