<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace chase_test_4\speakeasy_aPI;

/**
 * SpeakeasyAPI - Speakeasy API: The Speakeasy API allows teams to manage common operations with their APIs
 * 
 * https://docs.speakeasyapi.dev - The Speakeasy Platform Documentation
 * 
 * @package chase_test_4\speakeasy_aPI
 * @access public
 * @see https://docs.speakeasyapi.dev
 */
class SpeakeasyAPI
{
	public const SERVER_PROD = 'prod';
	
	public const SERVERS = [
		SpeakeasyAPI::SERVER_PROD => 'https://api.prod.speakeasyapi.dev',
	];
  	
    /**
     * REST APIs for managing ApiEndpoint entities
     * 
     * @var ApiEndpoints $$apiEndpoints
     */
	public ApiEndpoints $apiEndpoints;
	
    /**
     * REST APIs for managing Api entities
     * 
     * @var Apis $$apis
     */
	public Apis $apis;
	
    /**
     * REST APIs for managing embeds
     * 
     * @var Embeds $$embeds
     */
	public Embeds $embeds;
	
    /**
     * REST APIs for managing Version Metadata entities
     * 
     * @var Metadata $$metadata
     */
	public Metadata $metadata;
	
    /**
     * REST APIs for retrieving request information
     * 
     * @var Requests $$requests
     */
	public Requests $requests;
	
    /**
     * REST APIs for managing Schema entities
     * 
     * @var Schemas $$schemas
     */
	public Schemas $schemas;
		
	private SDKConfiguration $sdkConfiguration;

	/**
	 * Returns a new instance of the SDK builder used to configure and create the SDK instance.
	 * 
	 * @return SpeakeasyAPIBuilder
	 */
	public static function builder(): SpeakeasyAPIBuilder
	{
		return new SpeakeasyAPIBuilder();
	}

	/**
	 * @param SDKConfiguration $sdkConfiguration
	 */
	public function __construct(SDKConfiguration $sdkConfiguration)
	{
		$this->sdkConfiguration = $sdkConfiguration;
		
		$this->apiEndpoints = new ApiEndpoints($this->sdkConfiguration);
		
		$this->apis = new Apis($this->sdkConfiguration);
		
		$this->embeds = new Embeds($this->sdkConfiguration);
		
		$this->metadata = new Metadata($this->sdkConfiguration);
		
		$this->requests = new Requests($this->sdkConfiguration);
		
		$this->schemas = new Schemas($this->sdkConfiguration);
	}
}